# Generated by Django 5.0.3 on 2024-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
